# project info
site_name: Yet another insignficant
site_description: here, we share thoughts worth sharing
site_author: ayao
site_url: https://yet-another-insignficant.xyz



# Repositroy
repo_name: 'yet-another-insignficant'
repo_url: 'https://github.com/gearless-joeeee/yet_another_insigificant...'
# edit_uri: 'https://github.com/gearless-joeeee/yet_another_insigificant.../edit-landing/?ref='



# Copyright
copyright: 'referring from OI Wiki Team[https://oi-wiki.org]'


# Contents
nav:
    - Home: index.md
    - joy of js: 
      - for loop: deepJS/for-loop.md  
    - MkDocs:
        - getting-start: mkdocs/start.md
        - 配置文件解析: mkdocs/config.md

    - Sphinx: 
        - 介绍: 'sphinx/Sphinx - 介绍.md'
   
        - markdown配置: 'sphinx/Sphinx - markdown配置.md'
        - MathJax配置: './sphinx/Sphinx - MathJax.md'
        - bug: 'sphinx/Sphinx - bug.md'
    - Pandoc: 'pandoc-文档转换工具.md'
    - Readthedocs: 
        - 介绍: './readthedocs/ReadtheDocs - 介绍.md'


extra_css:
  - stylesheets/extra.css
# Theme
theme:
  name: material
  # custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# plugins:
#   - social
#   - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gearless-joeeee
    - icon: fontawesome/brands/twitter
    - icon: fontawesome/brands/linkedin


markdown_extensions:
  - toc:
        permalink: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


