# project info
site_name: Yet another insignficant
site_description: here, we share thoughts worth sharing
site_author: ayao
site_url: https://yet-another-insignficant.xyz



# Repositroy
repo_name: 'yet-another-insignficant'
repo_url: 'https://github.com/gearless-joeeee/yet_another_insigificant...'
# edit_uri: 'https://github.com/gearless-joeeee/yet_another_insigificant.../edit-landing/?ref='



# Copyright
copyright: 'referring from ayao(yet another insignficant...)'


# Contents
nav:
    - Home: index.md
    - joy of js: 
      - javascript/index.md
      - for loop: javascript/for-loop.md  
    - MkDocs:
        - getting-start: mkdocs/start.md
        - 配置文件解析: mkdocs/config.md
        - Reference:
          - reference/index.md
          - Admonitions: reference/admonitions.md
          - Annotations: reference/annotations.md
          - Buttons: reference/buttons.md
          - Code blocks: reference/code-blocks.md
          - Content tabs: reference/content-tabs.md
          - Data tables: reference/data-tables.md
          - Diagrams: reference/diagrams.md
          - Footnotes: reference/footnotes.md
          - Formatting: reference/formatting.md
          - Grids: reference/grids.md
          - Icons, Emojis: reference/icons-emojis.md
          - Images: reference/images.md
          - Lists: reference/lists.md
          - Math: reference/math.md
          - Tooltips: reference/tooltips.md
   
        - markdown配置: 'sphinx/Sphinx - markdown配置.md'
        - MathJax配置: './sphinx/Sphinx - MathJax.md'
        - bug: 'sphinx/Sphinx - bug.md'


extra_css:
  - stylesheets/extra.css
extra:
  status:
    new: Recently added
    deprecated: Will be removed soon
# Theme
theme:
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  features:
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    # - toc.follow
    - toc.integrate
    - navigation.instant.progress
    - navigation.instant.prefetch
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
    # annotation: 'material/material/plus-circle'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
  - social
#   - search

hooks:
  - hooks/on_env.py

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gearless-joeeee
    - icon: fontawesome/brands/twitter
    - icon: fontawesome/brands/linkedin


markdown_extensions:
# annoatian
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # - toc:
  #       permalink: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  


  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details

  - pymdownx.mark



