# project info
site_name: Hammond Developer Blog
site_description: coder, try to be enginner here, we share thoughts worth sharing
site_author: ayao
site_url: https://yet-another-insignficant.xyz



# Repositroy
repo_name: 'yet-another-insignficant'
repo_url: 'https://github.com/gearless-joeeee/yet_another_insigificant...'
# edit_uri: 'https://github.com/gearless-joeeee/yet_another_insigificant.../edit-landing/?ref='



# Copyright
copyright: coder, try to be engineer. here, we share thoughts worth sharing


# Contents
nav:
    - Home: index.md
    - Javascript内功修炼: 
      - javascript/index.md
      - 执行上下文: javascript/execution_context.md
      - 原型继承: javascript/prototype.md
      - 异步编程: javascript/async.md
      - 垃圾回收: javascript/garbage_collection.md
      - for loop: javascript/for-loop.md
      - responsive: javascript/responsive.md
      - event: javascript/event.md
    - Vue源码解读: vue/index.md
    - React源码解读: react/index.md
    - 前端工程化: enginner/index.md
    - 性能调优: performance/index.md
    - 前端框架生态库: ecosystem/index.md
    - 设计模式和系统架构: design/index.md
    - 数据结构与算法: algorithm/index.md
    - 项目随想录:
      - projects/index.md
      - 神舟医疗项目: 
        - Bug report: projects/shenzhou/bug.md
        - modules: 
          - 出诊计划: projects/shenzhou/modules/schedule.md
        - extensions:
          - 前后端数据通信: projects/shenzhou/extensions/ajax_axios.md
      - 图片: projects/image_solution.md
      - 网络和存储: projects/network_storage.md
      - 版本控制:  projects/version_control.md
      - 工欲善其事:
        - projects/developerTool/index.md
        - android studio: projects/developerTool/androidstudio.md
        - ssh: projects/developerTool/ssh.md
    - Bug report:
      - bugs/index.md
      - react-router-dom: bugs/react-router-dom.md
    # - Feature request:
    - Utils: 
      - utils/index.md
    - MkDocs:
        - getting-start: mkdocs/start.md
        - 配置文件解析: mkdocs/config.md
        - Reference:
          - reference/index.md
          - Admonitions: mkdocs/reference/admonitions.md
          - Annotations: mkdocs/reference/annotations.md
          - Buttons: mkdocs/reference/buttons.md
          - Code blocks: mkdocs/reference/code-blocks.md
          - Content tabs: mkdocs/reference/content-tabs.md
          - Data tables: mkdocs/reference/data-tables.md
          - Diagrams: mkdocs/reference/diagrams.md
          - Footnotes: mkdocs/reference/footnotes.md
          - Formatting: mkdocs/reference/formatting.md
          - Grids: mkdocs/reference/grids.md
          - Icons, Emojis: mkdocs/reference/icons-emojis.md
          - Images: mkdocs/reference/images.md
          - Lists: mkdocs/reference/lists.md
          - Math: mkdocs/reference/math.md
          - Tooltips: mkdocs/reference/tooltips.md


extra_css:
  - stylesheets/extra.css
extra:
  status:
    new: Recently added
    deprecated: Will be removed soon
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gearless-joeeee
    # - icon: fontawesome/brands/twitter
    # - icon: fontawesome/brands/linkedin

# Theme
theme:
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  features:
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    # - toc.follow
    - navigation.instant.progress
    - navigation.instant.prefetch
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
    # annotation: 'material/material/plus-circle'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
  - social
#   - search

hooks:
  - hooks/on_env.py

  

markdown_extensions:
  - footnotes
  - md_in_html # for image capation
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details




