# project info
site_name: Yet another insignficant
site_description: here, we share thoughts worth sharing
site_author: ayao
site_url: https://yet-another-insignficant.xyz



# Repositroy
repo_name: 'yet-another-insignficant'
repo_url: 'https://github.com/gearless-joeeee/yet_another_insigificant...'
# edit_uri: 'https://github.com/gearless-joeeee/yet_another_insigificant.../edit-landing/?ref='



# Copyright
copyright: 'referring from ayao(yet another insignficant...)'


# Contents
nav:
    - Home: index.md
    - joy of js: 
      - javascript/index.md
      - for loop: javascript/for-loop.md
      - responsive: javascript/responsive.md
    - MkDocs:
        - getting-start: mkdocs/start.md
        - 配置文件解析: mkdocs/config.md
        - Reference:
          - reference/index.md
          - Admonitions: mkdocs/reference/admonitions.md
          - Annotations: mkdocs/reference/annotations.md
          - Buttons: mkdocs/reference/buttons.md
          - Code blocks: mkdocs/reference/code-blocks.md
          - Content tabs: mkdocs/reference/content-tabs.md
          - Data tables: mkdocs/reference/data-tables.md
          - Diagrams: mkdocs/reference/diagrams.md
          - Footnotes: mkdocs/reference/footnotes.md
          - Formatting: mkdocs/reference/formatting.md
          - Grids: mkdocs/reference/grids.md
          - Icons, Emojis: mkdocs/reference/icons-emojis.md
          - Images: mkdocs/reference/images.md
          - Lists: mkdocs/reference/lists.md
          - Math: mkdocs/reference/math.md
          - Tooltips: mkdocs/reference/tooltips.md


extra_css:
  - stylesheets/extra.css
extra:
  status:
    new: Recently added
    deprecated: Will be removed soon
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gearless-joeeee
    # - icon: fontawesome/brands/twitter
    # - icon: fontawesome/brands/linkedin

# Theme
theme:
  name: material
  static_templates:
    - 404.html
  language: 'zh'
  features:
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    # - toc.follow
    - navigation.instant.progress
    - navigation.instant.prefetch
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
    # annotation: 'material/material/plus-circle'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
  - social
#   - search

hooks:
  - hooks/on_env.py

  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details




