# project info
site_name: shot for the moon
site_description: coder, try to be engineer here, we share thoughts worth sharing, xiyuan as my dev community name
site_author: ayao
site_url: https://yet-another-insignficant.xyz

# Repositroy
repo_name: "yet-another-insignficant"
repo_url: "https://github.com/gearless-joeeee/yet_another_insigificant..."
# edit_uri: 'https://github.com/gearless-joeeee/yet_another_insigificant.../edit-landing/?ref='

# Copyright
copyright: coder, try to be engineer. here, we share thoughts worth sharing

# Contents
nav:
  - YaoLin:
      - biograph.md
  - Home:
      - index.md
      - awesome blog: awesome-blog.md
  - Javascript内功修炼:
      - JS/index.md
      - JS/utils.md
      - 执行上下文: JS/execution_context.md
      - 原型继承: JS/prototype.md
      - 异步编程: JS/async.md
      - 垃圾回收: JS/garbage_collection.md
      - 事件循环: JS/event_loop.md
      - es6+: JS/es6+.md
      - for loop: JS/for-loop.md
      - 响应式: JS/responsive.md
      - event: JS/event.md
      - native utils polyfill 实现: JS/utils.md
      - layout.md
      - module.md
  - datav:
      - d3: datav/d3.md
  - webGL:
      - WebGL/index.md
      - spotlight: WebGL/spotlight.md
      - animation: WebGL/animation.md
      - interaction: WebGL/interaction.md
      - camera: WebGL/camera.md
      - light: WebGL/light.md
      - integrate: WebGL/integrate.md
  - webRTC:
      - webRTC/index.md
  - webGIS:
      - webGIS/index.md
  - 工程化落地:
      - tool-chain/cli.md
      - tool-chain/npm.md
      - tool-chain/index.md
      - tool-chain/cors.md
      - tool-chain/babel.md
      - tool-chain/webpack.md
      - tool-chain/resource-loading.md
  - 跨端开发实战:
      - crossplatform/index.md
  - 项目随想录:
      - projects/index.md
      - 大文件上传: projects/file-upload.md
      - 缓存和视图: projects/buffer-and-view.md
      - symbol: projects/symbol.md
      - 第三方库集成: projects/3rd-party-integration.md
      - 图片: projects/image_solution.md
      - 网络和存储: projects/network_storage.md
      - 版本控制: projects/version_control.md
  - 工欲善其事:
      - devtools/index.md
      - devtools/markdown.md
      - devtools/vscode.md
      - devtools/vim.md
      - devtools/cli.md

  - 走向全栈:
      - node/index.md
      - node/cookie.md
      - node/mongodb.md
  - web安全:
      - security/security.md
  - Vue源码解读: vue/index.md
  - React源码解读:
      - jsx: react/jsx.md
      - react/index.md
      - 环境搭建: react/setup.md
      - JSX转换: react/jsx-transpile.md
      - 初探reconciler: react/reconciler.md
      - 如何触发更新: react/update.md

  - 前端框架生态库: ecosystem/index.md
  - 设计模式和系统架构: design/index.md
  - 数据结构与算法: algorithm/index.md
  - Bug report:
      - ssh: bugs/ssh.md
      - react-router-dom: bugs/react-router-dom.md
  # - Feature request:
  # - android studio: projects/developerTool/androidstudio.md
  # - ssh: projects/developerTool/ssh.md
  - docs 定制化:
      - getting-start: custom/start.md

extra_css:
  - stylesheets/extra.css
extra:
  status:
    new: Recently added
    deprecated: Will be removed soon
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gearless-joeeee
    # - icon: fontawesome/brands/twitter
    # - icon: fontawesome/brands/linkedin

# Theme
theme:
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: "material/school"
  name: material
  static_templates:
    - 404.html
  language: "zh"
  features:
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    - toc.follow
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: "favicon.ico"
  font:
    text: "Fira Sans"
    code: "Fira Mono"

plugins:
  - social
  - blog:
      blog_dir: .
  - search
  - tags
#   - search

hooks:
  - hooks/on_env.py

markdown_extensions:
  - footnotes
  - md_in_html # for image capation
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
