packages:
  - packages/docs
  - packages/theme
  - packages/debug
  - packages/bump

catalog:
  # types
  "@types/node": "^22.10.1"
  tsx: "^4.19.3"
  typescript: "~5.6.2"

  # linting
  "@eslint/js": "^9.17.0"
  eslint: "^9.17.0"
  typescript-eslint: "^8.18.1"

  # vite
  vite: "^6.0.1"
  vite-plugin-inspect: "~0.8.6"
  unplugin-auto-import: "^0.19.0"
  unplugin-vue-components: "^0.28.0"
  "@mdit-vue/shared": "^2.1.3"
  sass: "^1.62.1"
  # vitepress
  vitepress: "^1.5.0"
  vitepress-plugin-group-icons: "^1.3.0"
  gray-matter: "^4.0.3"
  markdown-it-footnote: "^4.0.0"
  rough-notation: "0.5.1"
  tinyglobby: "^0.2.12"
  ms: "^2.1.3"

  # utils
  debug: "^4.3.4"

  # data fetching
  msw: "^2.7.0"

  # testing
  vitest: "^2.1.8"
