packages:
  - playground/client
  - interactive
  - docs
  - packages/**
catalog:
    # types
    "@types/node": "^22.10.1"
    "@types/react-dom": "^18.3.1"
    "@types/react": "^18.3.1"

    # linting
    "@eslint/js": "^9.17.0"
    eslint: "^9.17.0"
    typescript: "~5.6.2"
    typescript-eslint: "^8.18.1"


    vue: "^3.2.25"
    react: "^18.3.1"
    react-dom: "^18.3.0"
    
    # tailwind
    autoprefixer: "10.4.20"
    postcss: "8.4.49"
    postcss-each: ^1.1.0
    postcss-at-rules-variables: ^0.3.0
    postcss-custom-properties:  ^14.0.4
    tailwindcss: "3.4.17"

    # vite & vitepress
    "@vitejs/plugin-vue": "^5.2.1"
    "@vitejs/plugin-vue-jsx": "^4.1.1"
    "@vitejs/plugin-react": "^4.3.0"
    vite: "^6.0.1"
    vitepress: "^1.5.0"
    vitepress-plugin-group-icons: "^1.3.0"
    vite-plugin-inspect: "^0.10.2"
    "@shikijs/vitepress-twoslash": "^1.24.0"
    "@mdit-vue/shared": "^2.1.3"
    unplugin-auto-import: "^0.19.0"
    unplugin-vue-components: "^0.28.0"

    # tools
    "crawlee": "^3.12.1"
    "ofetch": "^1.4.1"
    simple-git: "^3.27.0"
    # test
    "vitest": "^2.1.8"