packages:
  - packages/**

catalog:
  # types
  "@types/node": "^22.10.1"
  node: 20.11.1

  # linting
  "@eslint/js": "^9.17.0"
  eslint: "^9.17.0"
  typescript: "~5.6.2"
  typescript-eslint: "^8.18.1"

  # vite
  vite: "^6.0.1"
  vite-plugin-inspect: "~0.8.6"
  unplugin-auto-import: "^0.19.0"
  unplugin-vue-components: "^0.28.0"

  # vitepress
  vitepress: "^1.5.0"
  vitepress-plugin-group-icons: "^1.3.0"

  # data fetching
  msw: "^2.7.0"

  # testing
  vitest: "^2.1.8"
